# Generated by Django 4.0.5 on 2022-06-22 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('thumbnail', models.FileField(upload_to='product/', verbose_name='썸네일')),
                ('desc', models.TextField(verbose_name='설명')),
                ('registered_date', models.DateField(auto_now_add=True, verbose_name='등록 일자')),
                ('exposed_end', models.DateField(verbose_name='노출 종료 일자')),
                ('price', models.IntegerField(default=0, verbose_name='상품 가격')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='수정 일자')),
                ('is_active', models.BooleanField(default='', null=True, verbose_name='활성화 여부')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
        ),
    ]
